version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es
    volumes_from:
      - esdata

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.1
    ports:
      - 5601:5601
    networks:
      - es
    depends_on:
      - elasticsearch

  esdata:
    image: busybox
    volumes:
      - /var/lib/elasticsearch

networks:
  es:
    driver: bridge